# Generated by Django 5.1.6 on 2025-08-14 21:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageAboutFond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Головне зображення для секції 'Про фонд'", upload_to='main_page_about/', verbose_name='Зображення фонду')),
                ('location', models.CharField(default='м. Львів, Україна', help_text='Місцезнаходження фонду (наприклад: м. Львів, Україна)', max_length=100, verbose_name='Локація')),
                ('fond_name', models.CharField(default='ArtRaise', help_text='Офіційна назва фонду', max_length=200, verbose_name='Назва фонду')),
                ('description', wagtail.fields.RichTextField(help_text='Детальна інформація про фонд з можливістю форматування', verbose_name='Опис фонду')),
                ('is_active', models.BooleanField(default=True, help_text='Чи відображається ця секція на сайті', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': "Секція 'Про фонд' (головна сторінка)",
                'verbose_name_plural': "Секції 'Про фонд' (головна сторінка)",
            },
        ),
    ]
