# Generated by Django 5.1.6 on 2025-08-15 08:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFondPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('image', models.ImageField(help_text="Головне зображення для сторінки 'Про фонд'", upload_to='about_fond/', verbose_name='Зображення фонду')),
                ('location', models.CharField(default='м. Львів, Україна', help_text='Місцезнаходження фонду (наприклад: м. Львів, Україна)', max_length=100, verbose_name='Локація')),
                ('fond_name', models.CharField(default='ArtRaise', help_text='Офіційна назва фонду', max_length=200, verbose_name='Назва фонду')),
                ('description', wagtail.fields.RichTextField(help_text='Детальна інформація про фонд з можливістю форматування', verbose_name='Опис фонду')),
            ],
            options={
                'verbose_name': "Сторінка 'Про фонд'",
                'verbose_name_plural': "Сторінки 'Про фонд'",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='MainPageAboutFond',
        ),
    ]
