# Generated by Django 5.1.6 on 2025-08-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutfondpage_delete_mainpageaboutfond'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головні сторінки',
            },
            bases=('wagtailcore.page',),
        ),
    ]
