# Generated by Django 5.1.6 on 2025-08-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAuthenticityCertsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_text', models.CharField(help_text='Заголовок секції (макс. 200 символів)', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(help_text='Зображення для секції автентичності сертифікатів', upload_to='authenticity_certs/', verbose_name='Зображення')),
                ('button_text', models.CharField(default='Переглянути сертифікати', help_text='Текст на кнопці (макс. 100 символів)', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, help_text="URL, куди веде кнопка (необов'язково)", verbose_name='Посилання кнопки')),
            ],
            options={
                'verbose_name': "Сторінка 'Home Authenticity Certs'",
                'verbose_name_plural': "Сторінки 'Home Authenticity Certs'",
            },
            bases=('wagtailcore.page',),
        ),
    ]
