# Generated by Django 5.1.6 on 2025-08-16 07:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homeauthenticitycertspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutfondpage',
            options={'verbose_name': "Сторінка 'Про фонд' (розширена)", 'verbose_name_plural': "Сторінки 'Про фонд' (розширені)"},
        ),
        migrations.RemoveField(
            model_name='aboutfondpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutfondpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutfondpage',
            name='location',
        ),
        migrations.AddField(
            model_name='aboutfondpage',
            name='content',
            field=wagtail.fields.StreamField([('description_block', 0), ('section', 6), ('media_with_caption', 11)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Короткий вступний абзац на початку сторінки', 'icon': 'pilcrow', 'label': 'Вступний опис'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Наприклад: 'Програма підтримки студентів'", 'label': 'Підзаголовок секції', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Короткий опис секції', 'label': 'Опис секції'}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст пункту'}), 4: ('wagtail.blocks.StructBlock', [[('item_text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Пункти секції'}), 6: ('wagtail.blocks.StructBlock', [[('subtitle', 1), ('description', 2), ('items', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Зображення'}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Відео'}), 9: ('wagtail.blocks.StreamBlock', [[('image', 7), ('video', 8)]], {'label': 'Медіа-файл', 'max_num': 1, 'min_num': 1}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Підпис до медіа', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('media_file', 9), ('caption', 10)]], {})}, default=[], verbose_name='Контент сторінки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutfondpage',
            name='fond_name',
            field=models.CharField(default='ArtRaise', max_length=200, verbose_name='Назва фонду (заголовок сторінки)'),
        ),
    ]
