# Generated by Django 5.1.6 on 2025-08-16 12:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_aboutfondpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfondpage',
            name='content',
            field=wagtail.fields.StreamField([('description_block', 0), ('section', 6), ('single_item', 8), ('media_with_caption', 15), ('text_with_caption', 18)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Короткий вступний абзац на початку сторінки', 'icon': 'pilcrow', 'label': 'Вступний опис'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Наприклад: 'Програма підтримки студентів' (необов'язково)", 'label': 'Підзаголовок секції', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': "Короткий опис секції (необов'язково)", 'label': 'Опис секції', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Текст пункту'}), 4: ('wagtail.blocks.StructBlock', [[('item_text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Пункти секції'}), 6: ('wagtail.blocks.StructBlock', [[('subtitle', 1), ('description', 2), ('items', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Текст окремого пункту'}), 8: ('wagtail.blocks.StructBlock', [[('item_text', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Вставте повну URL-адресу зображення з DigitalOcean Spaces', 'label': 'Посилання на зображення'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Короткий опис зображення для доступності', 'label': 'Альтернативний текст', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('url', 9), ('alt', 10)]], {'label': 'Зображення за URL'}), 12: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Відео'}), 13: ('wagtail.blocks.StreamBlock', [[('image_url', 11), ('video', 12)]], {'label': 'Медіа-файл', 'max_num': 1, 'min_num': 1}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Підпис до медіа', 'max_length': 255, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('media_file', 13), ('caption', 14)]], {}), 16: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': "Необов'язковий підпис після текстового блоку", 'label': 'Підпис до тексту', 'max_length': 255, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('text', 16), ('caption', 17)]], {})}, default=[], verbose_name='Контент сторінки'),
        ),
    ]
