# Generated by Django 5.1.6 on 2025-08-16 17:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_authenticitycertspage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalPageTemplate',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=200, verbose_name='Заголовок сторінки')),
                ('content', wagtail.fields.StreamField([('text', 1), ('media', 6), ('caption', 8), ('section', 14), ('single_item', 16), ('media_with_caption', 19), ('media_with_subtitle', 22), ('image_gallery', 25)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст', 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Вставте повну URL-адресу зображення з DigitalOcean Spaces', 'label': 'Посилання на зображення'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Короткий опис зображення для доступності', 'label': 'Альтернативний текст', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('url', 2), ('alt', 3)]], {'label': 'Зображення за URL'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Відео'}), 6: ('wagtail.blocks.StreamBlock', [[('image_url', 4), ('video', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Підпис', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('caption', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "Наприклад: 'Програма підтримки студентів' (необов'язково)", 'label': 'Підзаголовок секції', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': "Короткий опис секції (необов'язково)", 'label': 'Опис секції', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'label': 'Текст пункту'}), 12: ('wagtail.blocks.StructBlock', [[('item_text', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Пункти секції'}), 14: ('wagtail.blocks.StructBlock', [[('subtitle', 9), ('description', 10), ('items', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Текст окремого пункту'}), 16: ('wagtail.blocks.StructBlock', [[('item_text', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('image_url', 4), ('video', 5)]], {'label': 'Медіа-файл', 'max_num': 1, 'min_num': 1}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Підпис до медіа', 'max_length': 255, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('media_file', 17), ('caption', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Короткий заголовок для медіа-блоку', 'label': 'Підзаголовок (subtitle)', 'max_length': 255, 'required': False}), 21: ('wagtail.blocks.StreamBlock', [[('image_url', 4), ('video', 5)]], {'label': 'Медіа-файли'}), 22: ('wagtail.blocks.StructBlock', [[('subtitle', 20), ('media_file', 21), ('caption', 18)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Назва галереї / секції', 'label': 'Підзаголовок (subtitle)', 'max_length': 255, 'required': False}), 24: ('wagtail.blocks.ListBlock', (4,), {'label': 'Зображення'}), 25: ('wagtail.blocks.StructBlock', [[('subtitle', 23), ('images', 24)]], {})}, default=[], verbose_name='Контент сторінки')),
            ],
            options={
                'verbose_name': 'Універсальна сторінка-шаблон',
                'verbose_name_plural': 'Універсальні сторінки-шаблони',
            },
            bases=('wagtailcore.page',),
        ),
    ]
