# Generated by Django 5.1.6 on 2025-08-18 18:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_universalpagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfondpage',
            name='content',
            field=wagtail.fields.StreamField([('editor', 11)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 2'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 3'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 4'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'icon': 'pilcrow', 'label': 'Параграф'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Пункт списку'}), 5: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ul', 'label': 'Список з маркерами'}), 6: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ol', 'label': 'Нумерований список'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Оберіть зображення з бібліотеки', 'label': 'Зображення'}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Вбудований контент (відео, твіти тощо)'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ'}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Горизонтальна лінія для розділення контенту', 'icon': 'horizontal-line', 'label': 'Горизонтальна лінія'}), 11: ('wagtail.blocks.StreamBlock', [[('heading_2', 0), ('heading_3', 1), ('heading_4', 2), ('paragraph', 3), ('bulleted_list', 5), ('numbered_list', 6), ('image', 7), ('embed', 8), ('document', 9), ('horizontal_line', 10)]], {'label': 'Основний контент'})}, default=[], verbose_name='Контент сторінки'),
        ),
        migrations.AlterField(
            model_name='authenticitycertspage',
            name='content',
            field=wagtail.fields.StreamField([('editor', 11)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 2'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 3'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 4'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'icon': 'pilcrow', 'label': 'Параграф'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Пункт списку'}), 5: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ul', 'label': 'Список з маркерами'}), 6: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ol', 'label': 'Нумерований список'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Оберіть зображення з бібліотеки', 'label': 'Зображення'}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Вбудований контент (відео, твіти тощо)'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ'}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Горизонтальна лінія для розділення контенту', 'icon': 'horizontal-line', 'label': 'Горизонтальна лінія'}), 11: ('wagtail.blocks.StreamBlock', [[('heading_2', 0), ('heading_3', 1), ('heading_4', 2), ('paragraph', 3), ('bulleted_list', 5), ('numbered_list', 6), ('image', 7), ('embed', 8), ('document', 9), ('horizontal_line', 10)]], {'label': 'Основний контент'})}, default=[], verbose_name='Контент сторінки'),
        ),
        migrations.AlterField(
            model_name='universalpagetemplate',
            name='content',
            field=wagtail.fields.StreamField([('editor', 11)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 2'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 3'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h4', 'bold', 'italic'], 'icon': 'title', 'label': 'Заголовок 4'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'icon': 'pilcrow', 'label': 'Параграф'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Пункт списку'}), 5: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ul', 'label': 'Список з маркерами'}), 6: ('wagtail.blocks.ListBlock', (4,), {'icon': 'list-ol', 'label': 'Нумерований список'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Оберіть зображення з бібліотеки', 'label': 'Зображення'}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Вбудований контент (відео, твіти тощо)'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Документ'}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Горизонтальна лінія для розділення контенту', 'icon': 'horizontal-line', 'label': 'Горизонтальна лінія'}), 11: ('wagtail.blocks.StreamBlock', [[('heading_2', 0), ('heading_3', 1), ('heading_4', 2), ('paragraph', 3), ('bulleted_list', 5), ('numbered_list', 6), ('image', 7), ('embed', 8), ('document', 9), ('horizontal_line', 10)]], {'label': 'Основний контент'})}, default=[], verbose_name='Контент сторінки'),
        ),
    ]
