services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py migrate --settings=project.settings.dev &&
             python manage.py runserver --settings=project.settings.dev 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=artraise
      - DB_USER=artraise
      - DB_PASS=artraise
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artraise
      - POSTGRES_USER=artraise
      - POSTGRES_PASSWORD=artraise
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
    depends_on:
      - backend
    env_file:
      - ./front/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
volumes:
  dev-db_data: