# Generated by Django 5.1.6 on 2025-02-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='event',
        ),
    ]
