# Generated by Django 5.1.6 on 2025-02-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('bio_text', models.TextField(max_length=1000)),
                ('style', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('expression_type', models.CharField(max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
