# Generated by Django 5.1.6 on 2025-04-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_author_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_author',
            field=models.ImageField(blank=True, null=True, upload_to='images_author/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_text',
            field=models.TextField(max_length=3000),
        ),
    ]
