# Generated by Django 5.1.6 on 2025-05-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_image_author_alter_author_bio_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_author',
            field=models.ImageField(upload_to='images_author/'),
        ),
    ]
