# Generated by Django 5.1.6 on 2025-06-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_alter_author_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_author',
            field=models.ImageField(upload_to='images_author/'),
        ),
    ]
