# Generated by Django 5.1.6 on 2025-07-22 18:33

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artpiece', '0009_artpiecebuyform_is_processed_and_more'),
        ('authors', '0008_alter_author_image_author'),
        ('events', '0003_event_events_even_start_d_d4b514_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок слайда (макс. 200 символов)', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='Подзаголовок или описание слайда (макс. 300 символов)', max_length=300, verbose_name='Подзаголовок')),
                ('image', models.ImageField(help_text='Изображение для слайда. Рекомендуемый размер: 1920x1080px', upload_to='slider/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения слайда (чем меньше число, тем выше в списке)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли этот слайд на сайте', verbose_name='Активный')),
                ('custom_link', models.URLField(blank=True, help_text='Произвольная ссылка для перехода (если не указаны связанные объекты)', validators=[django.core.validators.URLValidator()], verbose_name='Произвольная ссылка')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Подробное описание слайда (отображается при необходимости)', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('linked_artpiece', models.ForeignKey(blank=True, help_text='Произведение искусства, на которое ведет слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artpiece.artpiece', verbose_name='Связанное произведение')),
                ('linked_author', models.ForeignKey(blank=True, help_text='Автор, на страницу которого ведет слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author', verbose_name='Связанный автор')),
                ('linked_event', models.ForeignKey(blank=True, help_text='Событие, на страницу которого ведет слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event', verbose_name='Связанное событие')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order'], name='slider_slid_order_cdcae6_idx'), models.Index(fields=['is_active'], name='slider_slid_is_acti_84db75_idx'), models.Index(fields=['created_at'], name='slider_slid_created_215b77_idx')],
            },
        ),
    ]
