# Generated by Django 5.1.6 on 2025-07-25 10:11

import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import зззззззз0щ, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0009_artpiecebuyform_is_processed_and_more'),
        ('authors', '0008_alter_author_image_author'),
        ('events', '0003_event_events_even_start_d_d4b514_idx_and_more'),
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайди'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='custom_link',
            field=models.URLField(blank=True, help_text="Довільне посилання для переходу (якщо не вказані пов'язані об'єкти)", validators=[django.core.validators.URLValidator()], verbose_name='Довільне посилання'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Докладний опис слайда (відображається за необхідності)', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(help_text='Зображення для слайда. Рекомендуваний розмір: 1920x1080px', upload_to='slider/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показувати цей слайд на сайті', verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='linked_artpiece',
            field=models.ForeignKey(blank=True, help_text='Мистецьке твір, на яке веде слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artpiece.artpiece', verbose_name="Пов'язане мистецьке твір"),
        ),
        migrations.AlterField(
            model_name='slide',
            name='linked_author',
            field=models.ForeignKey(blank=True, help_text='Автор, на сторінку якого веде слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author', verbose_name="Пов'язаний автор"),
        ),
        migrations.AlterField(
            model_name='slide',
            name='linked_event',
            field=models.ForeignKey(blank=True, help_text='Подія, на сторінку якої веде слайд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event', verbose_name="Пов'язане подія"),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок відображення слайда (чим менше число, тим вище в списку)', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Підзаголовок або опис слайда (макс. 300 символів)', max_length=300, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(help_text='Заголовок слайда (макс. 200 символів)', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
