# Generated by Django 5.1.6 on 2025-02-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('painting', 'живопис'), ('sculpture', 'скульптура'), ('graphics', 'графіка'), ('architecture', 'архітектура'), ('aplied_art', 'прикладне_мистецтво'), ('design', 'дизайн')], max_length=20)),
                ('material', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creating_date_start', models.IntegerField(blank=True, null=True)),
                ('creating_date_end', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artpieces', to='authors.author')),
            ],
        ),
    ]
