# Generated by Django 5.1.6 on 2025-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
