# Generated by Django 5.1.6 on 2025-02-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0002_artpiece_certificate'),
        ('authors', '0003_remove_author_event'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artpiece',
            index=models.Index(fields=['price'], name='artpiece_ar_price_2865b9_idx'),
        ),
        migrations.AddIndex(
            model_name='artpiece',
            index=models.Index(fields=['material'], name='artpiece_ar_materia_589858_idx'),
        ),
        migrations.AddIndex(
            model_name='artpiece',
            index=models.Index(fields=['theme'], name='artpiece_ar_theme_51e2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='artpiece',
            index=models.Index(fields=['author'], name='artpiece_ar_author__7a2b46_idx'),
        ),
        migrations.AddIndex(
            model_name='artpiece',
            index=models.Index(fields=['type'], name='artpiece_ar_type_f76cc7_idx'),
        ),
    ]
