# Generated by Django 5.1.6 on 2025-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0003_artpiece_artpiece_ar_price_2865b9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artpiece',
            name='artpiece_ar_price_2865b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='artpiece',
            name='artpiece_ar_materia_589858_idx',
        ),
        migrations.RemoveIndex(
            model_name='artpiece',
            name='artpiece_ar_theme_51e2e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='artpiece',
            name='artpiece_ar_author__7a2b46_idx',
        ),
        migrations.RemoveIndex(
            model_name='artpiece',
            name='artpiece_ar_type_f76cc7_idx',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='image_artpiece',
            field=models.ImageField(blank=True, null=True, upload_to='images_artpiece/'),
        ),
    ]
