# Generated by Django 5.1.6 on 2025-04-09 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0004_remove_artpiece_artpiece_ar_price_2865b9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='format',
            field=models.CharField(blank=True, choices=[('small', 'малий'), ('medium', 'середній'), ('big', 'великий')], max_length=10),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='gamma',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='orientation',
            field=models.CharField(blank=True, choices=[('square', 'квадратна'), ('portrait', 'портретна'), ('landscape', 'пейзажна')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='creating_date_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='creating_date_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
