# Generated by Django 5.1.6 on 2025-05-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0005_artpiece_dominant_color_artpiece_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='orientation',
            field=models.CharField(choices=[('square', 'квадратна'), ('portrait', 'портретна'), ('landscape', 'пейзажна')], max_length=10),
        ),
    ]
