# Generated by Django 5.1.6 on 2025-06-01 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0006_alter_artpiece_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 1, 7, 22, 20, 866579, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
