# Generated by Django 5.1.6 on 2025-07-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0007_artpiece_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPieceBuyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artpiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_requests', to='artpiece.artpiece')),
            ],
        ),
    ]
