# Generated by Django 5.1.6 on 2025-07-08 17:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0008_artpiecebuyform'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiecebuyform',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artpiecebuyform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA'),
        ),
    ]
