# Generated by Django 5.1.6 on 2025-07-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0009_artpiecebuyform_is_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Англійська назва категорії (для API)', max_length=100, unique=True, verbose_name='Назва англійською')),
                ('name_ua', models.CharField(help_text='Українська назва категорії (для інтерфейсу)', max_length=100, unique=True, verbose_name='Назва українською')),
                ('description', models.TextField(blank=True, help_text='Опис категорії', verbose_name='Опис')),
                ('image_url', models.ImageField(blank=True, help_text='Зображення для представлення категорії', null=True, upload_to='categories/', verbose_name='Зображення категорії')),
                ('is_active', models.BooleanField(default=True, help_text='Чи відображається категорія на сайті', verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення (менше число = вище в списку)', verbose_name='Порядок')),
                ('slug', models.SlugField(blank=True, help_text='URL-дружня назва (автоматично генерується)', max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name_ua'],
                'indexes': [models.Index(fields=['is_active'], name='artpiece_ca_is_acti_f86699_idx'), models.Index(fields=['order'], name='artpiece_ca_order_0f2b00_idx'), models.Index(fields=['slug'], name='artpiece_ca_slug_25c9ad_idx')],
            },
        ),
        migrations.AddField(
            model_name='artpiece',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категорія твору мистецтва', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artpieces', to='artpiece.category', verbose_name='Категорія'),
        ),
    ]
