# Generated by Django 5.1.6 on 2025-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpiece', '0012_finalize_category_refactoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Англійська назва тега (максимум 30 символів)', max_length=30, unique=True, verbose_name='Назва тега')),
                ('name_ua', models.CharField(help_text='Українська назва тега (максимум 30 символів)', max_length=30, unique=True, verbose_name='Назва українською')),
                ('slug', models.SlugField(blank=True, help_text='URL-дружня назва (автоматично генерується)', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Опціональний опис тега', verbose_name='Опис')),
                ('color', models.CharField(blank=True, default='#007bff', help_text='Колір тега у форматі HEX (наприклад, #007bff)', max_length=7, verbose_name='Колір')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Порядок відображення (менше число = вище в списку)', verbose_name='Пріоритет')),
                ('is_active', models.BooleanField(default=True, help_text='Чи відображається тег на сайті', verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='artpiece',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги твору мистецтва (максимум 5 тегів)', related_name='artpieces', to='artpiece.tag', verbose_name='Теги'),
        ),
    ]
