# Generated by Django 5.1.6 on 2025-02-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_phone_number_customuser_createdon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='createdOn',
            new_name='created_on',
        ),
    ]
