# Generated by Django 5.1.6 on 2025-02-07 15:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fullname', models.CharField(max_length=255)),
                ('bio_text', wagtail.fields.RichTextField()),
                ('style', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('expression_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
