# Generated by Django 5.1.6 on 2025-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_created_at_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.CharField(max_length=2000)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
