# Generated by Django 5.1.6 on 2025-07-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_calltoaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calltoaction',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
