# Generated by Django 5.1.6 on 2025-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_rename_created_ad_calltoaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, choices=[('AP', 'Про платформу'), ('PAD', 'Оплата та доставка'), ('TS', 'Техпідтримка'), ('C', 'Колекціонери')], default=None, max_length=3, null=True),
        ),
    ]
