# Generated by Django 5.1.6 on 2025-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_in_call_to_action',
            field=models.BooleanField(default=False),
        ),
    ]
