# Generated by Django 5.1.6 on 2025-08-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_faq_is_active_faq_order_faq_show_in_call_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='show_in_call_to_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_in_how_to_buy',
            field=models.BooleanField(default=False, verbose_name='Показувати в How to Buy'),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_in_question_answer',
            field=models.BooleanField(default=False, verbose_name='Показувати в Q&A'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='show_in_call_to_action',
            field=models.BooleanField(default=False, verbose_name='Показувати в Call-to-Action'),
        ),
    ]
