# Generated by Django 5.1.6 on 2025-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0008_faqcategory_alter_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToBuyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Заголовок блоку англійською мовою (може містити HTML)', max_length=200, verbose_name='Заголовок англійською')),
                ('title_ua', models.CharField(help_text='Заголовок блоку українською мовою (може містити HTML)', max_length=200, verbose_name='Заголовок українською')),
                ('description_en', models.TextField(help_text='Детальний опис блоку англійською мовою', verbose_name='Опис англійською')),
                ('description_ua', models.TextField(help_text='Детальний опис блоку українською мовою', verbose_name='Опис українською')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок відображення (менше число = вище в списку)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Чи відображається блок на сайті', verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': "Блок 'Як купити'",
                'verbose_name_plural': "Блоки 'Як купити'",
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='faq_howtobu_is_acti_22b6eb_idx'), models.Index(fields=['order'], name='faq_howtobu_order_3bcda1_idx')],
            },
        ),
    ]
